"use client";

import {useMemo,useState} from "react";
import QRCode from "qrcode";
import type {Tool} from "@/data/tools";

type Field={key:string;label:string;type?:"number"|"date"|"text"|"select";placeholder?:string;defaultValue?:string;options?:{value:string;label:string}[]};
type Result={title:string;value:string;lines?:string[]};
type Config={fields:Field[];calculate:(v:Record<string,string>)=>Result;note?:string};

const n=(v:string)=>Number(v||0);
const money=(x:number)=>new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",maximumFractionDigits:2}).format(Number.isFinite(x)?x:0);
function taxProgressive(x:number){const b:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[150000,0],[150000,.05],[200000,.1],[250000,.15],[250000,.2],[1000000,.25],[3000000,.3],[Infinity,.35]];let left=Math.max(0,x),tax=0;for(const[cap,rate]of b){const part=Math.min(left,cap);tax+=part*rate;left-=part;if(left<=0)break}return tax}
function bahtText(input:number){if(!Number.isFinite(input))return"ศูนย์บาทถ้วน";const [intRaw,decRaw]=Math.abs(input).toFixed(2).split(".");const nums=["ศูนย์","หนึ่ง","สอง","สาม","สี่","ห้า","หก","เจ็ด","แปด","เก้า"],pos=["","สิบ","ร้อย","พัน","หมื่น","แสน"];const chunk=(s:string)=>{let out="";s=s.padStart(6,"0");for(let i=0;i<6;i++){const d=Number(s[i]),p=5-i;if(!d)continue;if(p===1&&d===1)out+="สิบ";else if(p===1&&d===2)out+="ยี่สิบ";else if(p===0&&d===1&&out)out+="เอ็ด";else out+=nums[d]+pos[p]}return out};const read=(s:string):string=>s.length<=6?chunk(s):read(s.slice(0,-6))+"ล้าน"+chunk(s.slice(-6));return(input<0?"ลบ":"")+(Number(intRaw)?read(intRaw):"ศูนย์")+"บาท"+(Number(decRaw)?chunk(decRaw)+"สตางค์":"ถ้วน")}

const configs:Record<string,Config>={
"thai-income-tax":{fields:[{key:"annual",label:"รายได้รวมทั้งปี",type:"number",placeholder:"600000"},{key:"deduct",label:"ค่าลดหย่อนรวม",type:"number",defaultValue:"60000"},{key:"withheld",label:"ภาษีหักไว้แล้ว",type:"number",defaultValue:"0"}],calculate:v=>{const annual=n(v.annual),expense=Math.min(annual*.5,100000),taxable=Math.max(0,annual-expense-n(v.deduct)),tax=taxProgressive(taxable),balance=tax-n(v.withheld);return{title:"ภาษีประมาณการ",value:money(tax),lines:["เงินได้สุทธิ "+money(taxable),balance>0?"คาดว่าต้องจ่ายเพิ่ม "+money(balance):"คาดว่าอาจได้คืน "+money(Math.abs(balance))]}},note:"เป็นการประมาณเพื่อวางแผน โปรดยืนยันกับกรมสรรพากรก่อนใช้งานจริง"},
"net-salary":{fields:[{key:"salary",label:"เงินเดือนต่อเดือน",type:"number",placeholder:"30000"},{key:"tax",label:"ภาษีหักต่อเดือน",type:"number",defaultValue:"0"}],calculate:v=>{const s=n(v.salary),ss=Math.min(s,17500)*.05;return{title:"เงินรับสุทธิประมาณ",value:money(s-ss-n(v.tax)),lines:["ประกันสังคมประมาณ "+money(ss)]}}},
"social-security":{fields:[{key:"salary",label:"ฐานเงินเดือน",type:"number",placeholder:"25000"}],calculate:v=>{const base=Math.min(Math.max(n(v.salary),1650),17500);return{title:"เงินสมทบประมาณ",value:money(base*.05),lines:["ฐานคำนวณ "+money(base)]}}},
"severance-pay":{fields:[{key:"salary",label:"เงินเดือนล่าสุด",type:"number",placeholder:"25000"},{key:"years",label:"อายุงาน (ปี)",type:"number",placeholder:"4"}],calculate:v=>{const y=n(v.years),days=y>=20?400:y>=10?300:y>=6?240:y>=3?180:y>=1?90:y>=.33?30:0;return{title:"ค่าชดเชยประมาณ",value:money(n(v.salary)/30*days),lines:["จำนวนวันอ้างอิงเบื้องต้น "+days+" วัน"]}},note:"ใช้เป็นค่าประมาณเบื้องต้นเท่านั้น"},
"overtime":{fields:[{key:"salary",label:"เงินเดือน",type:"number",placeholder:"20000"},{key:"hours",label:"ชั่วโมง OT",type:"number",placeholder:"10"},{key:"rate",label:"ตัวคูณ OT",type:"number",defaultValue:"1.5"}],calculate:v=>{const hourly=n(v.salary)/30/8;return{title:"ค่า OT ประมาณ",value:money(hourly*n(v.hours)*n(v.rate)),lines:["ค่าจ้างต่อชั่วโมง "+money(hourly)]}}},
"service-years":{fields:[{key:"start",label:"วันเริ่มงาน",type:"date"},{key:"end",label:"วันที่คำนวณ",type:"date"}],calculate:v=>{const a=new Date(v.start),b=v.end?new Date(v.end):new Date(),days=Math.max(0,Math.floor((b.getTime()-a.getTime())/86400000));return{title:"ระยะเวลาทำงาน",value:Math.floor(days/365.25)+" ปี",lines:["รวมประมาณ "+days.toLocaleString("th-TH")+" วัน"]}}},
"withholding-tax":{fields:[{key:"amount",label:"ยอดก่อนหัก",type:"number",placeholder:"10000"},{key:"rate",label:"อัตราหัก (%)",type:"number",defaultValue:"3"}],calculate:v=>{const t=n(v.amount)*n(v.rate)/100;return{title:"ยอดรับสุทธิ",value:money(n(v.amount)-t),lines:["ภาษีหัก "+money(t)]}}},
"compound-interest":{fields:[{key:"p",label:"เงินต้น",type:"number",placeholder:"100000"},{key:"rate",label:"ดอกเบี้ยต่อปี (%)",type:"number",placeholder:"4"},{key:"years",label:"จำนวนปี",type:"number",placeholder:"5"}],calculate:v=>{const p=n(v.p),total=p*Math.pow(1+n(v.rate)/100,n(v.years));return{title:"เงินปลายทาง",value:money(total),lines:["ดอกเบี้ยรวม "+money(total-p)]}}},
"percentage":{fields:[{key:"percent",label:"เปอร์เซ็นต์ (%)",type:"number",placeholder:"15"},{key:"value",label:"ของจำนวน",type:"number",placeholder:"1200"}],calculate:v=>({title:"ผลลัพธ์",value:(n(v.value)*n(v.percent)/100).toLocaleString("th-TH",{maximumFractionDigits:2})})},
"discount":{fields:[{key:"price",label:"ราคาเดิม",type:"number",placeholder:"1990"},{key:"discount",label:"ส่วนลด (%)",type:"number",placeholder:"20"}],calculate:v=>{const save=n(v.price)*n(v.discount)/100;return{title:"ราคาหลังลด",value:money(n(v.price)-save),lines:["ประหยัด "+money(save)]}}},
"vat":{fields:[{key:"amount",label:"ยอดเงิน",type:"number",placeholder:"1000"},{key:"mode",label:"รูปแบบ",type:"select",defaultValue:"add",options:[{value:"add",label:"เพิ่ม VAT 7%"},{value:"remove",label:"ถอด VAT 7%"}]}],calculate:v=>{const a=n(v.amount);if(v.mode==="remove"){const before=a/1.07;return{title:"ราคาก่อน VAT",value:money(before),lines:["VAT "+money(a-before)]}}const vat=a*.07;return{title:"ราคารวม VAT",value:money(a+vat),lines:["VAT "+money(vat)]}}},
"profit":{fields:[{key:"cost",label:"ต้นทุน",type:"number",placeholder:"500"},{key:"sell",label:"ราคาขาย",type:"number",placeholder:"750"}],calculate:v=>{const p=n(v.sell)-n(v.cost);return{title:"กำไร",value:money(p),lines:["Margin "+(n(v.sell)?p/n(v.sell)*100:0).toFixed(2)+"%"]}}},
"selling-price":{fields:[{key:"cost",label:"ต้นทุน",type:"number",placeholder:"500"},{key:"markup",label:"กำไรจากต้นทุน (%)",type:"number",placeholder:"30"}],calculate:v=>({title:"ราคาขายแนะนำ",value:money(n(v.cost)*(1+n(v.markup)/100))})},
"online-shop-profit":{fields:[{key:"sell",label:"ราคาขาย",type:"number",placeholder:"1000"},{key:"cost",label:"ต้นทุนสินค้า",type:"number",placeholder:"600"},{key:"fee",label:"ค่าธรรมเนียม (%)",type:"number",placeholder:"10"}],calculate:v=>{const fee=n(v.sell)*n(v.fee)/100;return{title:"กำไรสุทธิประมาณ",value:money(n(v.sell)-n(v.cost)-fee),lines:["ค่าธรรมเนียม "+money(fee)]}}},
"loan-payment":{fields:[{key:"p",label:"ยอดกู้",type:"number",placeholder:"1000000"},{key:"rate",label:"ดอกเบี้ยต่อปี (%)",type:"number",placeholder:"6"},{key:"years",label:"ระยะเวลา (ปี)",type:"number",placeholder:"10"}],calculate:v=>loanResult(n(v.p),n(v.rate),n(v.years))},
"home-loan":{fields:[{key:"p",label:"วงเงินกู้บ้าน",type:"number",placeholder:"3000000"},{key:"rate",label:"ดอกเบี้ยเฉลี่ยต่อปี (%)",type:"number",placeholder:"4"},{key:"years",label:"ระยะเวลา (ปี)",type:"number",defaultValue:"30"}],calculate:v=>loanResult(n(v.p),n(v.rate),n(v.years))},
"car-loan":{fields:[{key:"price",label:"ราคารถ",type:"number",placeholder:"800000"},{key:"down",label:"เงินดาวน์ (%)",type:"number",defaultValue:"20"},{key:"rate",label:"ดอกเบี้ยคงที่ต่อปี (%)",type:"number",defaultValue:"2.5"},{key:"months",label:"จำนวนงวด",type:"number",defaultValue:"60"}],calculate:v=>{const down=n(v.price)*n(v.down)/100,p=n(v.price)-down,interest=p*n(v.rate)/100*(n(v.months)/12),pay=(p+interest)/Math.max(1,n(v.months));return{title:"ค่างวดรถประมาณ",value:money(pay),lines:["เงินดาวน์ "+money(down),"ยอดจัด "+money(p),"ดอกเบี้ยรวม "+money(interest)]}}},
"credit-card-payoff":{fields:[{key:"debt",label:"ยอดหนี้",type:"number",placeholder:"50000"},{key:"rate",label:"ดอกเบี้ยต่อปี (%)",type:"number",defaultValue:"16"},{key:"pay",label:"ยอดจ่ายต่อเดือน",type:"number",placeholder:"5000"}],calculate:v=>{let debt=n(v.debt),months=0,interest=0;const r=n(v.rate)/1200,pay=n(v.pay);while(debt>0&&months<600&&pay>0){const i=debt*r;interest+=i;debt=debt+i-pay;months++;if(debt>n(v.debt)*2)break}return{title:"ระยะเวลาประมาณ",value:months>=600?"มากกว่า 50 ปี":months+" เดือน",lines:["ดอกเบี้ยรวมประมาณ "+money(interest)]}}},
"interest-compare":{fields:[{key:"p",label:"เงินต้น",type:"number",placeholder:"500000"},{key:"a",label:"อัตรา A (%)",type:"number",placeholder:"3"},{key:"b",label:"อัตรา B (%)",type:"number",placeholder:"5"},{key:"years",label:"จำนวนปี",type:"number",defaultValue:"1"}],calculate:v=>{const ia=n(v.p)*n(v.a)/100*n(v.years),ib=n(v.p)*n(v.b)/100*n(v.years);return{title:"ส่วนต่างดอกเบี้ย",value:money(Math.abs(ia-ib)),lines:["A "+money(ia),"B "+money(ib)]}}},
"land-unit":{fields:[{key:"rai",label:"ไร่",type:"number",defaultValue:"0"},{key:"ngan",label:"งาน",type:"number",defaultValue:"0"},{key:"wah",label:"ตารางวา",type:"number",defaultValue:"0"}],calculate:v=>{const wah=n(v.rai)*400+n(v.ngan)*100+n(v.wah);return{title:"พื้นที่รวม",value:wah.toLocaleString("th-TH")+" ตร.ว.",lines:[(wah*4).toLocaleString("th-TH")+" ตร.ม."]}}},
"land-price":{fields:[{key:"wah",label:"พื้นที่ (ตร.ว.)",type:"number",placeholder:"100"},{key:"price",label:"ราคาต่อ ตร.ว.",type:"number",placeholder:"25000"}],calculate:v=>({title:"ราคาที่ดินรวม",value:money(n(v.wah)*n(v.price))})},
"property-transfer-fee":{fields:[{key:"price",label:"ราคาประเมิน",type:"number",placeholder:"2000000"},{key:"rate",label:"ค่าธรรมเนียม (%)",type:"number",defaultValue:"2"}],calculate:v=>({title:"ค่าธรรมเนียมประมาณ",value:money(n(v.price)*n(v.rate)/100)}),note:"ค่าใช้จ่ายจริงอาจมีรายการอื่นเพิ่มเติม"},
"age":{fields:[{key:"birth",label:"วันเกิด",type:"date"}],calculate:v=>{const d=new Date(v.birth),now=new Date();let age=now.getFullYear()-d.getFullYear();const m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))age--;return{title:"อายุปัจจุบัน",value:Math.max(0,age)+" ปี"}}},
"date-difference":{fields:[{key:"start",label:"วันที่เริ่ม",type:"date"},{key:"end",label:"วันที่สิ้นสุด",type:"date"}],calculate:v=>({title:"ระยะห่าง",value:Math.abs(Math.floor((new Date(v.end).getTime()-new Date(v.start).getTime())/86400000)).toLocaleString("th-TH")+" วัน"})},
"buddhist-year":{fields:[{key:"year",label:"กรอกปี",type:"number",placeholder:"2569"},{key:"mode",label:"รูปแบบ",type:"select",defaultValue:"be",options:[{value:"be",label:"พ.ศ. → ค.ศ."},{value:"ce",label:"ค.ศ. → พ.ศ."}]}],calculate:v=>({title:"ปีที่แปลงแล้ว",value:String(v.mode==="be"?n(v.year)-543:n(v.year)+543)})},
"holiday-count":{fields:[{key:"start",label:"วันที่เริ่ม",type:"date"},{key:"end",label:"วันที่สิ้นสุด",type:"date"}],calculate:v=>{let a=new Date(v.start),b=new Date(v.end),count=0,guard=0;if(a>b)[a,b]=[b,a];for(const d=new Date(a);d<=b&&guard<5000;d.setDate(d.getDate()+1),guard++)if(d.getDay()!==0&&d.getDay()!==6)count++;return{title:"วันทำการโดยประมาณ",value:count+" วัน",lines:["ยังไม่หักวันหยุดราชการ"]}}},
"countdown":{fields:[{key:"target",label:"วันที่เป้าหมาย",type:"date"}],calculate:v=>{const days=Math.ceil((new Date(v.target).getTime()-new Date().setHours(0,0,0,0))/86400000);return{title:"เหลือเวลา",value:days>=0?days+" วัน":"ผ่านมาแล้ว "+Math.abs(days)+" วัน"}}},
"electricity-bill":{fields:[{key:"units",label:"หน่วยไฟ (kWh)",type:"number",placeholder:"300"},{key:"rate",label:"อัตราเฉลี่ย/หน่วย",type:"number",defaultValue:"4.2"}],calculate:v=>{const sub=n(v.units)*n(v.rate),vat=sub*.07;return{title:"ค่าไฟประมาณ",value:money(sub+vat),lines:["ก่อน VAT "+money(sub),"VAT "+money(vat)]}},note:"เป็นแบบจำลองอัตราเฉลี่ย ไม่ใช่ใบแจ้งหนี้จากผู้ให้บริการ"},
"water-bill":{fields:[{key:"units",label:"หน่วยน้ำ",type:"number",placeholder:"20"},{key:"rate",label:"อัตราเฉลี่ย/หน่วย",type:"number",defaultValue:"12"}],calculate:v=>({title:"ค่าน้ำประมาณ",value:money(n(v.units)*n(v.rate))})},
"fuel-cost":{fields:[{key:"distance",label:"ระยะทาง (กม.)",type:"number",placeholder:"300"},{key:"eff",label:"กม./ลิตร",type:"number",placeholder:"15"},{key:"price",label:"ราคาน้ำมัน/ลิตร",type:"number",placeholder:"35"}],calculate:v=>{const liters=n(v.distance)/Math.max(.01,n(v.eff));return{title:"ค่าน้ำมันประมาณ",value:money(liters*n(v.price)),lines:["น้ำมันประมาณ "+liters.toFixed(2)+" ลิตร"]}}},
"bmi":{fields:[{key:"weight",label:"น้ำหนัก (กก.)",type:"number",placeholder:"65"},{key:"height",label:"ส่วนสูง (ซม.)",type:"number",placeholder:"170"}],calculate:v=>{const h=n(v.height)/100,bmi=n(v.weight)/(h*h||1),label=bmi<18.5?"น้ำหนักต่ำ":bmi<23?"ปกติ":bmi<25?"น้ำหนักเกิน":bmi<30?"อ้วนระดับ 1":"อ้วนระดับ 2 ขึ้นไป";return{title:"BMI",value:bmi.toFixed(2),lines:[label]}}},
"calories":{fields:[{key:"sex",label:"เพศ",type:"select",defaultValue:"male",options:[{value:"male",label:"ชาย"},{value:"female",label:"หญิง"}]},{key:"weight",label:"น้ำหนัก",type:"number",placeholder:"65"},{key:"height",label:"ส่วนสูง",type:"number",placeholder:"170"},{key:"age",label:"อายุ",type:"number",placeholder:"30"}],calculate:v=>{const b=v.sex==="male"?10*n(v.weight)+6.25*n(v.height)-5*n(v.age)+5:10*n(v.weight)+6.25*n(v.height)-5*n(v.age)-161;return{title:"BMR โดยประมาณ",value:Math.round(b).toLocaleString("th-TH")+" kcal/วัน"}}},
"split-bill":{fields:[{key:"total",label:"ยอดรวม",type:"number",placeholder:"1500"},{key:"people",label:"จำนวนคน",type:"number",placeholder:"4"}],calculate:v=>({title:"ต่อคน",value:money(n(v.total)/Math.max(1,n(v.people)))})},
"unit-converter":{fields:[{key:"value",label:"ระยะทาง",type:"number",placeholder:"10"},{key:"mode",label:"แปลง",type:"select",defaultValue:"km-mi",options:[{value:"km-mi",label:"กม. → ไมล์"},{value:"mi-km",label:"ไมล์ → กม."}]}],calculate:v=>({title:"ผลลัพธ์",value:(v.mode==="km-mi"?n(v.value)*.621371:n(v.value)/.621371).toFixed(4)+(v.mode==="km-mi"?" ไมล์":" กม.")})},
"baht-text":{fields:[{key:"amount",label:"จำนวนเงิน",type:"number",placeholder:"1250.50"}],calculate:v=>({title:"ข้อความ",value:bahtText(n(v.amount))})}
};
function loanResult(p:number,rate:number,years:number):Result{const m=rate/1200,nm=Math.max(1,years*12),pay=m===0?p/nm:p*m*Math.pow(1+m,nm)/(Math.pow(1+m,nm)-1);return{title:"ค่างวดประมาณต่อเดือน",value:money(pay),lines:["ยอดชำระรวมประมาณ "+money(pay*nm)]}}

function Calculator({config}:{config:Config}){const init=Object.fromEntries(config.fields.map(f=>[f.key,f.defaultValue||""]));const[v,setV]=useState<Record<string,string>>(init);const[result,setResult]=useState<Result|null>(null);return <div className="workspace-grid"><form className="workspace-card" onSubmit={e=>{e.preventDefault();setResult(config.calculate(v))}}><h2>ข้อมูลที่ใช้คำนวณ</h2><div className="form-grid">{config.fields.map(f=><label className="field" key={f.key}><span>{f.label}</span>{f.type==="select"?<select value={v[f.key]||f.defaultValue||""} onChange={e=>setV({...v,[f.key]:e.target.value})}>{f.options?.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:<input type={f.type||"number"} inputMode={f.type==="number"?"decimal":undefined} value={v[f.key]||""} placeholder={f.placeholder} onChange={e=>setV({...v,[f.key]:e.target.value})} required/>}</label>)}</div><button className="primary-btn" type="submit">คำนวณผลลัพธ์ →</button>{config.note&&<p className="form-note">{config.note}</p>}</form><div className="result-card"><span className="eyebrow">ผลลัพธ์</span>{result?<div className="result-content"><h3>{result.title}</h3><strong>{result.value}</strong>{result.lines?.map(x=><p key={x}>{x}</p>)}</div>:<div className="result-placeholder"><span>✦</span><h3>พร้อมคำนวณ</h3><p>กรอกข้อมูลแล้วกดคำนวณ</p></div>}</div></div>}

function RandomBox({slug}:{slug:string}){const[input,setInput]=useState(""),[teams,setTeams]=useState("2"),[result,setResult]=useState("");function run(){if(slug==="random-number"){const[a,b]=input.split(",").map(Number);const min=Number.isFinite(a)?a:1,max=Number.isFinite(b)?b:100;setResult(String(Math.floor(Math.random()*(max-min+1))+min))}else if(slug==="random-name"){const list=input.split(/\n|,/).map(x=>x.trim()).filter(Boolean);setResult(list.length?list[Math.floor(Math.random()*list.length)]:"กรุณาใส่รายชื่อ")}else if(slug==="random-team"){const list=input.split(/\n|,/).map(x=>x.trim()).filter(Boolean).sort(()=>Math.random()-.5),count=Math.max(2,Number(teams)||2),groups=Array.from({length:count},()=>[] as string[]);list.forEach((x,i)=>groups[i%count].push(x));setResult(groups.map((g,i)=>"ทีม "+(i+1)+": "+g.join(", ")).join("\n"))}else if(slug==="password-generator"){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";const len=Math.min(64,Math.max(8,Number(input)||16));setResult(Array.from({length:len},()=>chars[Math.floor(Math.random()*chars.length)]).join(""))}else setResult(Math.random()>.5?"YES — ใช่":"NO — ไม่")}return <div className="workspace-grid"><div className="workspace-card"><h2>ตั้งค่าการสุ่ม</h2>{slug!=="yes-no"&&<label className="field"><span>{slug==="random-number"?"ช่วง เช่น 1,100":slug==="password-generator"?"ความยาวรหัสผ่าน":"รายชื่อ"}</span>{slug==="random-name"||slug==="random-team"?<textarea rows={7} value={input} onChange={e=>setInput(e.target.value)}/>:<input value={input} onChange={e=>setInput(e.target.value)}/>}</label>}{slug==="random-team"&&<label className="field"><span>จำนวนทีม</span><input type="number" value={teams} onChange={e=>setTeams(e.target.value)}/></label>}<button className="primary-btn" onClick={run}>สุ่มเลย ✦</button></div><div className="result-card"><span className="eyebrow">ผลการสุ่ม</span><div className="random-result">{result||"กดปุ่มเพื่อเริ่มสุ่ม"}</div></div></div>}

function promptPayload(id:string,amount?:number){const clean=id.replace(/\D/g,""),type=clean.length===10?"01":"02",target=clean.length===10?"0066"+clean.slice(1):clean,fmt=(i:string,v:string)=>i+String(v.length).padStart(2,"0")+v,merchant="0016A000000677010111"+type+String(target.length).padStart(2,"0")+target;let p=fmt("00","01")+fmt("01","12")+fmt("29",merchant)+fmt("58","TH")+fmt("53","764");if(amount&&amount>0)p+=fmt("54",amount.toFixed(2));p+=fmt("63","0000");let crc=0xFFFF,s=p.slice(0,-4);for(let c=0;c<s.length;c++){crc^=s.charCodeAt(c)<<8;for(let i=0;i<8;i++){crc=crc&0x8000?(crc<<1)^0x1021:crc<<1;crc&=0xFFFF}}return s+crc.toString(16).toUpperCase().padStart(4,"0")}
function QRBox({prompt=false}:{prompt?:boolean}){const[text,setText]=useState(""),[amount,setAmount]=useState(""),[url,setUrl]=useState("");async function make(){const value=prompt?promptPayload(text,n(amount)||undefined):text;if(value)setUrl(await QRCode.toDataURL(value,{width:560,margin:2,errorCorrectionLevel:"M"}))}return <div className="workspace-grid"><div className="workspace-card"><h2>{prompt?"ข้อมูลรับเงิน":"ข้อมูลใน QR"}</h2><label className="field"><span>{prompt?"เบอร์โทรหรือเลขประจำตัวที่ผูกพร้อมเพย์":"ข้อความหรือลิงก์"}</span><input value={text} onChange={e=>setText(e.target.value)} placeholder={prompt?"0812345678":"https://example.com"}/></label>{prompt&&<label className="field"><span>จำนวนเงิน (ไม่บังคับ)</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="100.00"/></label>}<button className="primary-btn" onClick={make}>สร้าง QR Code →</button><p className="form-note">สร้างในเบราว์เซอร์และไม่บันทึกค่าที่กรอก</p></div><div className="result-card qr-result"><span className="eyebrow">QR Preview</span>{url?<><img src={url} alt="QR Code"/><a className="download-btn" href={url} download={prompt?"promptpay-qr.png":"qr-code.png"}>ดาวน์โหลด PNG ↓</a></>:<div className="result-placeholder"><span>▦</span><h3>QR จะปรากฏตรงนี้</h3></div>}</div></div>}

function ImageBox({mode}:{mode:"resize"|"compress"|"convert"}){const[file,setFile]=useState<File|null>(null),[width,setWidth]=useState("1200"),[quality,setQuality]=useState(".8"),[format,setFormat]=useState("image/webp"),[out,setOut]=useState("");function run(){if(!file)return;const img=new Image();img.onload=()=>{const w=mode==="resize"?Math.max(1,Number(width)||img.width):img.width,canvas=document.createElement("canvas");canvas.width=w;canvas.height=Math.round(w*img.height/img.width);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(img,0,0,canvas.width,canvas.height);const mime=mode==="convert"?format:file.type==="image/png"&&mode==="resize"?"image/png":"image/webp";setOut(canvas.toDataURL(mime,Math.min(1,Math.max(.1,Number(quality)||.8))))};img.src=URL.createObjectURL(file)}return <div className="workspace-grid"><div className="workspace-card"><h2>เลือกรูปภาพ</h2><label className="upload-zone"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><strong>{file?file.name:"แตะเพื่อเลือกรูปภาพ"}</strong><span>ประมวลผลในเบราว์เซอร์</span></label>{mode==="resize"&&<label className="field"><span>ความกว้างใหม่ (px)</span><input type="number" value={width} onChange={e=>setWidth(e.target.value)}/></label>}{mode==="compress"&&<label className="field"><span>คุณภาพ 0.1 - 1</span><input type="number" min=".1" max="1" step=".1" value={quality} onChange={e=>setQuality(e.target.value)}/></label>}{mode==="convert"&&<label className="field"><span>รูปแบบไฟล์</span><select value={format} onChange={e=>setFormat(e.target.value)}><option value="image/webp">WebP</option><option value="image/png">PNG</option><option value="image/jpeg">JPG</option></select></label>}<button className="primary-btn" onClick={run}>ประมวลผลรูป →</button></div><div className="result-card image-result"><span className="eyebrow">ผลลัพธ์</span>{out?<><img src={out} alt="รูปที่ประมวลผล"/><a className="download-btn" href={out} download="krobkrueng-image">ดาวน์โหลดรูป ↓</a></>:<div className="result-placeholder"><span>▧</span><h3>รูปใหม่จะแสดงตรงนี้</h3></div>}</div></div>}

function YoutubeBox(){const[url,setUrl]=useState("");const id=useMemo(()=>url.match(/(?:youtu\.be\/|v=|shorts\/)([\w-]{11})/)?.[1]||"",[url]);return <div className="workspace-grid"><div className="workspace-card"><h2>ลิงก์วิดีโอ</h2><label className="field"><span>YouTube URL</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..."/></label></div><div className="result-card image-result"><span className="eyebrow">ภาพปก</span>{id?<><img src={"https://i.ytimg.com/vi/"+id+"/maxresdefault.jpg"} alt="YouTube thumbnail"/><a className="download-btn" href={"https://i.ytimg.com/vi/"+id+"/maxresdefault.jpg"} target="_blank" rel="noreferrer">เปิดภาพต้นฉบับ ↗</a></>:<div className="result-placeholder"><span>▷</span><h3>วางลิงก์ YouTube</h3></div>}</div></div>}
function DreamBox(){const[q,setQ]=useState("");const data=[["งู","ตามความเชื่อมักเชื่อมโยงกับความสัมพันธ์หรือการเปลี่ยนแปลง"],["น้ำ","มักสื่อถึงอารมณ์และสภาวะภายใน"],["ปลา","มักถูกมองเป็นสัญลักษณ์ของความอุดมสมบูรณ์"],["บ้าน","มักเชื่อมโยงกับครอบครัวและความมั่นคง"],["บิน","มักตีความถึงอิสระหรือความทะเยอทะยาน"]];const m=data.find(([k])=>q.includes(k));return <div className="workspace-grid"><div className="workspace-card"><h2>ค้นหาคำในความฝัน</h2><label className="field"><span>คำสำคัญ</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="งู น้ำ ปลา บ้าน"/></label><p className="form-note">เพื่อความบันเทิงตามความเชื่อเท่านั้น</p></div><div className="result-card"><span className="eyebrow">ความหมายตัวอย่าง</span><div className="result-content"><h3>{q||"รอคำค้น"}</h3><p>{q?(m?.[1]||"ยังไม่มีคำนี้ในคลัง V1"):"กรอกคำสำคัญเพื่อค้นหา"}</p></div></div></div>}
function BetaBox({tool}:{tool:Tool}){return <div className="beta-box"><span className="badge muted">BETA</span><h2>{tool.name} อยู่ในชุดทดสอบ V1</h2><p>หน้าและโครงสร้างพร้อมแล้ว แต่โมดูลประมวลผลขั้นสูงของเครื่องมือนี้ยังไม่เปิดเต็มรูปแบบ เพื่อไม่แสดงผลลัพธ์หรือไฟล์ที่อาจทำให้เข้าใจผิด</p><p>เครื่องมือคำนวณ QR และรูปภาพหลักของ V1 ใช้งานได้จริงแล้ว</p></div>}

export default function ToolWorkspace({tool}:{tool:Tool}){if(configs[tool.slug])return <Calculator config={configs[tool.slug]}/>;if(["random-number","random-name","random-team","password-generator","yes-no"].includes(tool.slug))return <RandomBox slug={tool.slug}/>;if(tool.slug==="promptpay-qr")return <QRBox prompt/>;if(tool.slug==="qr-code")return <QRBox/>;if(tool.slug==="resize-image")return <ImageBox mode="resize"/>;if(tool.slug==="compress-image")return <ImageBox mode="compress"/>;if(tool.slug==="image-converter")return <ImageBox mode="convert"/>;if(tool.slug==="youtube-thumbnail")return <YoutubeBox/>;if(tool.slug==="dream-meaning")return <DreamBox/>;return <BetaBox tool={tool}/>}
